2024-04-13T20:07:46 {"cpu": 0.8564453125, "cpu_total": 4, "cpu_usage": 0.214111328125, "memory": 5619.0, "memory_total": 24291.0, "memory_usage": 0.23132024206496232, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038866.006276, "uuid": "c9a1e8ef98b042d8b9d0d43a8ac8d56b"}
2024-04-13T20:07:46 {"block_run_id": 297, "block_uuid": "load_coinbase_histodata", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 76, BlockRun 297: pipeline coinbase_histo block load_coinbase_histodata", "timestamp": 1713038866.5534, "uuid": "fb0e452135a74484b181d4a3538ed846"}
2024-04-13T20:07:47 {"cpu": 0.8564453125, "cpu_total": 4, "cpu_usage": 0.214111328125, "memory": 5666.0, "memory_total": 24291.0, "memory_usage": 0.23325511506319213, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038867.072919, "uuid": "7317919dac9b47eca04d0d8273c13b29"}
2024-04-13T20:07:55 {"cpu": 0.8525390625, "cpu_total": 4, "cpu_usage": 0.213134765625, "memory": 5686.0, "memory_total": 24291.0, "memory_usage": 0.23407846527520482, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038875.545959, "uuid": "1bbcf3b5e0c24fbe9cc77c55dcfd3645"}
2024-04-13T20:08:06 {"cpu": 0.8486328125, "cpu_total": 4, "cpu_usage": 0.212158203125, "memory": 5697.0, "memory_total": 24291.0, "memory_usage": 0.23453130789181179, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038886.280225, "uuid": "9b342e78752b4791aec9faf3a665b712"}
2024-04-13T20:08:15 {"cpu": 0.8388671875, "cpu_total": 4, "cpu_usage": 0.209716796875, "memory": 5701.0, "memory_total": 24291.0, "memory_usage": 0.23469597793421432, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038895.986258, "uuid": "40c86cd315b846edb18a626a58b611f9"}
2024-04-13T20:08:20 {"block_run_id": 297, "block_uuid": "load_coinbase_histodata", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 297 (block_uuid: load_coinbase_histodata) completes.", "timestamp": 1713038900.140347, "uuid": "496fb54fda9a457db10502b5aeaba94a"}
2024-04-13T20:08:25 {"cpu": 0.8349609375, "cpu_total": 4, "cpu_usage": 0.208740234375, "memory": 5643.0, "memory_total": 24291.0, "memory_usage": 0.23230826231937754, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038905.428417, "uuid": "38bd680e964649cab68ea8d5230771a9"}
2024-04-13T20:08:25 {"block_run_id": 298, "block_uuid": "fill_na", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 76, BlockRun 298: pipeline coinbase_histo block fill_na", "timestamp": 1713038905.915832, "uuid": "88c64e959b234d0cb14d1b48747169a0"}
2024-04-13T20:08:27 {"block_run_id": 298, "block_uuid": "fill_na", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 298 (block_uuid: fill_na) completes.", "timestamp": 1713038907.664858, "uuid": "e8649a6f5f834275af048e7be1902583"}
2024-04-13T20:08:36 {"cpu": 0.83642578125, "cpu_total": 4, "cpu_usage": 0.2091064453125, "memory": 5645.0, "memory_total": 24291.0, "memory_usage": 0.23239059734057882, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038916.042829, "uuid": "d6f3e7c77cea48efbf35871a847e1f35"}
2024-04-13T20:08:36 {"block_run_id": 299, "block_uuid": "tranform_histo_datatypes", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 76, BlockRun 299: pipeline coinbase_histo block tranform_histo_datatypes", "timestamp": 1713038916.334404, "uuid": "f6fc224a32f44ffe960d3d557104c7c5"}
2024-04-13T20:08:45 {"cpu": 0.89208984375, "cpu_total": 4, "cpu_usage": 0.2230224609375, "memory": 6131.0, "memory_total": 24291.0, "memory_usage": 0.2523980074924869, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038925.781927, "uuid": "67a41dd7c1424ea5975ad0064e146699"}
2024-04-13T20:08:55 {"block_run_id": 299, "block_uuid": "tranform_histo_datatypes", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 299 (block_uuid: tranform_histo_datatypes) completes.", "timestamp": 1713038935.108415, "uuid": "b19b459664b24409aa60f3dd26d4ae3f"}
2024-04-13T20:08:56 {"cpu": 0.90380859375, "cpu_total": 4, "cpu_usage": 0.2259521484375, "memory": 5645.0, "memory_total": 24291.0, "memory_usage": 0.23239059734057882, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038936.19598, "uuid": "73524298fc0940df92c5daffa665bdb6"}
2024-04-13T20:08:56 {"block_run_id": 300, "block_uuid": "transform_token_to_name", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 76, BlockRun 300: pipeline coinbase_histo block transform_token_to_name", "timestamp": 1713038936.759466, "uuid": "aa04a6b2a70f4659b7ee93812c090fc4"}
2024-04-13T20:09:04 {"block_run_id": 300, "block_uuid": "transform_token_to_name", "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "EXCEPTION", "message": "BlockRun 300 (block_uuid: transform_token_to_name) failed.", "timestamp": 1713038944.042777, "uuid": "052715d701614769a7571b1974ee3e69", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1258, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1167, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1473, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1629, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 51, in transform\n  File \"<string>\", line 40, in transform\nAttributeError: 'dict' object has no attribute 'withColumn'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 750, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 92, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1654, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1163, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'dict' object has no attribute 'withColumn'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1258, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1167, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1473, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1629, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 51, in transform
  File "<string>", line 40, in transform
AttributeError: 'dict' object has no attribute 'withColumn'
2024-04-13T20:09:06 {"cpu": 0.91552734375, "cpu_total": 4, "cpu_usage": 0.2288818359375, "memory": 5646.0, "memory_total": 24291.0, "memory_usage": 0.23243176485117945, "pipeline_run_id": 76, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 76 in schedule 3 is alive.", "timestamp": 1713038946.055334, "uuid": "20dd454200c841f4a33ba9a4c57df084"}
