2024-04-13T20:00:35 {"cpu": 0.7421875, "cpu_total": 4, "cpu_usage": 0.185546875, "memory": 5580.0, "memory_total": 24291.0, "memory_usage": 0.2297147091515376, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038435.418857, "uuid": "9355da41ed4a45dab52fe658ac6ef89b"}
2024-04-13T20:00:35 {"block_run_id": 292, "block_uuid": "load_coinbase_histodata", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 75, BlockRun 292: pipeline coinbase_histo block load_coinbase_histodata", "timestamp": 1713038435.692631, "uuid": "f0b9b0e6684947c89fc8140e5c571ffc"}
2024-04-13T20:00:35 {"cpu": 0.7421875, "cpu_total": 4, "cpu_usage": 0.185546875, "memory": 5624.0, "memory_total": 24291.0, "memory_usage": 0.2315260796179655, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038435.752628, "uuid": "ef36718989d14efb9daed9e3c9e550e4"}
2024-04-13T20:00:45 {"cpu": 0.7333984375, "cpu_total": 4, "cpu_usage": 0.183349609375, "memory": 5633.0, "memory_total": 24291.0, "memory_usage": 0.2318965872133712, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038445.296608, "uuid": "6e8790569a9e4ce7acaac1fde9931ed7"}
2024-04-13T20:00:55 {"cpu": 0.74658203125, "cpu_total": 4, "cpu_usage": 0.1866455078125, "memory": 5638.0, "memory_total": 24291.0, "memory_usage": 0.23210242476637438, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038455.665748, "uuid": "5db0d8cb9b644ae993ae46795af9fe99"}
2024-04-13T20:01:06 {"cpu": 0.73779296875, "cpu_total": 4, "cpu_usage": 0.1844482421875, "memory": 5642.0, "memory_total": 24291.0, "memory_usage": 0.2322670948087769, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038466.280427, "uuid": "6e24f75b4ce74495b4371161bb34a462"}
2024-04-13T20:01:08 {"block_run_id": 292, "block_uuid": "load_coinbase_histodata", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 292 (block_uuid: load_coinbase_histodata) completes.", "timestamp": 1713038468.154742, "uuid": "91cc1eb4f4304ac99c42b20e00eab22c"}
2024-04-13T20:01:15 {"cpu": 0.74609375, "cpu_total": 4, "cpu_usage": 0.1865234375, "memory": 5580.0, "memory_total": 24291.0, "memory_usage": 0.2297147091515376, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038475.72686, "uuid": "104851eff646465284305a18e1768366"}
2024-04-13T20:01:16 {"block_run_id": 293, "block_uuid": "fill_na", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 75, BlockRun 293: pipeline coinbase_histo block fill_na", "timestamp": 1713038476.095302, "uuid": "72a9e4bbf25f4320bb5378b013ccdf35"}
2024-04-13T20:01:17 {"block_run_id": 293, "block_uuid": "fill_na", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 293 (block_uuid: fill_na) completes.", "timestamp": 1713038477.191287, "uuid": "c6a1c15ece97468881759cabe3e86b3d"}
2024-04-13T20:01:25 {"cpu": 0.7490234375, "cpu_total": 4, "cpu_usage": 0.187255859375, "memory": 5581.0, "memory_total": 24291.0, "memory_usage": 0.22975587666213823, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038485.300437, "uuid": "b6fea680362b46a387d2185a1b251751"}
2024-04-13T20:01:25 {"block_run_id": 294, "block_uuid": "tranform_histo_datatypes", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 75, BlockRun 294: pipeline coinbase_histo block tranform_histo_datatypes", "timestamp": 1713038485.66339, "uuid": "88d47ecdbcd04994addef8fce2eac012"}
2024-04-13T20:01:36 {"cpu": 0.7841796875, "cpu_total": 4, "cpu_usage": 0.196044921875, "memory": 6094.0, "memory_total": 24291.0, "memory_usage": 0.2508748096002635, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038496.221661, "uuid": "68a19295866749219d7dc68a81c21285"}
2024-04-13T20:01:45 {"cpu": 0.81396484375, "cpu_total": 4, "cpu_usage": 0.2034912109375, "memory": 6411.0, "memory_total": 24291.0, "memory_usage": 0.26392491046066446, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038505.849205, "uuid": "abca85bea0e54cb39015e5500d2e2689"}
2024-04-13T20:01:46 {"block_run_id": 294, "block_uuid": "tranform_histo_datatypes", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 294 (block_uuid: tranform_histo_datatypes) completes.", "timestamp": 1713038506.700789, "uuid": "bd17b804f4894e4db68af804d5868b34"}
2024-04-13T20:01:55 {"cpu": 0.83740234375, "cpu_total": 4, "cpu_usage": 0.2093505859375, "memory": 5577.0, "memory_total": 24291.0, "memory_usage": 0.2295912066197357, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038515.402398, "uuid": "d6d21b49bd354c95a6df324a76240c6b"}
2024-04-13T20:01:55 {"block_run_id": 295, "block_uuid": "transform_token_to_name", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 75, BlockRun 295: pipeline coinbase_histo block transform_token_to_name", "timestamp": 1713038515.773793, "uuid": "b0e182d64ea14caea794e42a2d3dacbd"}
2024-04-13T20:02:03 {"block_run_id": 295, "block_uuid": "transform_token_to_name", "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "EXCEPTION", "message": "BlockRun 295 (block_uuid: transform_token_to_name) failed.", "timestamp": 1713038523.220182, "uuid": "6255093071ab4859a2a5a4c16e767d86", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1258, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1167, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1473, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1629, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 51, in transform\n  File \"<string>\", line 40, in transform\nAttributeError: 'dict' object has no attribute 'withColumn'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 750, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 92, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1654, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1163, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'dict' object has no attribute 'withColumn'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1258, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1167, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1473, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1629, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 51, in transform
  File "<string>", line 40, in transform
AttributeError: 'dict' object has no attribute 'withColumn'
2024-04-13T20:02:06 {"cpu": 0.87646484375, "cpu_total": 4, "cpu_usage": 0.2191162109375, "memory": 5580.0, "memory_total": 24291.0, "memory_usage": 0.2297147091515376, "pipeline_run_id": 75, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 75 in schedule 3 is alive.", "timestamp": 1713038526.014051, "uuid": "eae4cf6bdf584d2492c0c50381a6a89c"}
